baseURL: "https://vamshiragipani.netlify.app/"
languageCode: en-us
title: Vamshi Ragipani
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Vamshi Ragipani"
    subtitle: I'm a Software Engineer at [**Broadridge**](https://www.broadridge.com/), passionate about tech. I hold a degree in computer engineering and internship experience at  [**Accenture**](https://www.accenture.com/in-en), Technology excites me and I am always in awe of the change it drives in the world. Certain skills that I have worked with include Data Structures and Algorithms (Java, C#), Web Development (NodeJs, MySQL, Angular), Linux OS (with Go) & Machine Learning (Python). And what I might lack in skills I make up for with my determination to learn. Beyond coding, I'm an artist and an actor, always up for new challenges.
    imageUrl: "home/Vamshi.jpg"
    imageWidth: 220
    imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "vamshirajragipani@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/VamshiRagipani"
    - name: "github"
      url: "https://github.com/VamshiRagipani"
    - name: "youtube"
      url: "https://www.youtube.com/VamshiRagipani"
    - name: "cv"
      url: "https://drive.google.com/file/d/1U6Gg2RnHSCthtWLbZJBlAEI3V1WGjZty/view"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
